ui.title: "JDB-NET ǀ Gatus"
ui.header: "JDB-NET ǀ Gatus"
ui.logo: "https://assets.jdbnet.co.uk/linktree/logo-400x400.png"
ui.link: "https://www.jdbnet.co.uk"

storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@10.10.8.21:5432/${POSTGRES_DB}?sslmode=disable"

endpoint-websites: &websites
  group: Websites
  interval: 1m
  client:
    timeout: 10s
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"

endpoint-services: &services
  group: Services
  interval: 1m
  conditions:
    - "[CONNECTED] == true"

endpoints:
  - name: LittleLink
    <<: *websites
    url: "https://www.jdbnet.co.uk"

  - name: Apps
    <<: *websites
    url: "https://apps.jdbnet.co.uk/windows/Activator.cmd"

  - name: Assets
    <<: *websites
    url: "https://assets.jdbnet.co.uk/logo/64x64.png"

  - name: Docs
    <<: *websites
    url: "https://docs.jdbnet.co.uk/Proxmox/Build%20your%20own%20Proxmox%20LXC%20Template/"
  
  - name: Mastodon
    <<: *websites
    url: "https://social.jdbnet.co.uk/explore"

  - name: Plant Pot RP Docs
    <<: *websites
    url: "https://plantpotrp.jdbnet.co.uk/Robberies/Store%20Robberies/"

  - name: Plex
    <<: *services
    url: "tcp://10.10.8.14:32400"

  - name: Fireshare
    <<: *websites
    url: "https://fireshare.jdbnet.co.uk"
